version: '3.7'

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: ${BOT_NAME}
        links:
            - mongodb

    mongodb:
        image: mongo:latest
        restart: unless-stopped
        ports:
            -   "27018:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        volumes:
            - ./mongodb/data:/data/db


    mongo-express:
        image: mongo-express:latest
        restart: always
        env_file:
            - .env
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
