version: '3'

services:
#    bot:
#        image: "${BOT_IMAGE_NAME:-tg_bot-image}"
#        container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
#        stop_signal: SIGINT
#        build:
#            context: .
#        working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
#        volumes:
#            - botdata:/data
#        command: python3 -m app
#        restart: always
#        networks:
#            - backend
#        links:
#            - mongo


    mongo:
        image: 'mongo:latest'
        command: mongod --port 27018
        restart: always
        ports:
            - 27018:27018
        env_file:
            - ".env"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        env_file:
            - ".env"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
        depends_on:
            - mongo
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    mongodbdata:
        driver: local
    botdata:
        driver: local
