version: '3.7'

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: ${BOT_NAME}
        volumes:
            - ./bot/data:/data
        links:
            - mongodb

    mongodb:
        image: mongo:latest
        restart: unless-stopped
        ports:
            - "27018:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGODB_DATA_DIR: /data/db
            MONGODB_LOG_DIR: /dev/null
        volumes:
            - ./mongodb/data:/data/db

    mongo-express:
        image: mongo-express
        restart: unless-stopped
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongorootuser
            ME_CONFIG_MONGODB_ADMINPASSWORD: PswdRoot
            ME_CONFIG_MONGODB_URL: mongodb://mongorootuser:PswdRoot@mongodb:27017/
